In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
df = pd.read_csv("/Users/prayagregmi/Downloads/carPrice3.csv")
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2                       NaN      gas        std       four   
4       5          2                       NaN      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

### Checking the number of columns and rows in the dataset

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 202 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            202 non-null    int64  
 1   symboling         202 non-null    int64  
 2   CarName           202 non-null    object 
 3   fueltype          202 non-null    object 
 4   aspiration        202 non-null    object 
 5   doornumber        202 non-null    object 
 6   carbody           202 non-null    object 
 7   drivewheel        202 non-null    object 
 8   enginelocation    202 non-null    object 
 9   wheelbase         202 non-null    float64
 10  carlength         202 non-null    float64
 11  carwidth          202 non-null    float64
 12  carheight         202 non-null    float64
 13  curbweight        202 non-null    int64  
 14  enginetype        202 non-null    object 
 15  cylindernumber    202 non-null    object 
 16  enginesize        202 non-null    int64  
 17  fu

In [81]:
# Dropping the cols which have null values
df.dropna(inplace=True)

#### Dropping the columns which are not important to predict the car price

In [96]:
df.drop(columns=['symboling','aspiration','carbody','enginelocation','enginelocation','wheelbase','carwidth','carlength','carheight'],inplace=True)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 202 entries, 0 to 204
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   CarName         202 non-null    object 
 1   fueltype        202 non-null    object 
 2   doornumber      202 non-null    object 
 3   drivewheel      202 non-null    object 
 4   enginetype      202 non-null    object 
 5   cylindernumber  202 non-null    object 
 6   enginesize      202 non-null    int64  
 7   horsepower      202 non-null    int64  
 8   citympg         202 non-null    int64  
 9   highwaympg      202 non-null    int64  
 10  price           202 non-null    float64
dtypes: float64(1), int64(4), object(6)
memory usage: 18.9+ KB


#### After dropping multiple columns the data processing part is finished

## Data Analysis

In [120]:
for col in df.columns:
    print("Unique values of "+col)
    print(df[col].unique())
    print("=====\n")

Unique values of CarName
['alfa-romero giulia' 'alfa-romero stelvio' 'alfa-romero Quadrifoglio'
 'audi fox' 'audi 5000' 'audi 4000' 'audi 5000s (diesel)' 'bmw 320i'
 'bmw x1' 'bmw x3' 'bmw z4' 'bmw x4' 'bmw x5' 'chevrolet impala'
 'chevrolet monte carlo' 'chevrolet vega 2300' 'dodge rampage'
 'dodge challenger se' 'dodge d200' 'dodge monaco (sw)'
 'dodge colt hardtop' 'dodge colt (sw)' 'dodge coronet custom'
 'dodge dart custom' 'dodge coronet custom (sw)' 'honda civic'
 'honda civic cvcc' 'honda accord cvcc' 'honda accord lx'
 'honda civic 1500 gl' 'honda accord' 'honda civic 1300' 'honda prelude'
 'honda civic (auto)' 'isuzu MU-X' 'isuzu D-Max' 'isuzu D-Max V-Cross'
 'jaguar xj' 'jaguar xf' 'jaguar xk' 'maxda rx3' 'maxda glc deluxe'
 'mazda rx2 coupe' 'mazda rx-4' 'mazda glc deluxe' 'mazda 626' 'mazda glc'
 'mazda rx-7 gs' 'mazda glc 4' 'mazda glc custom l' 'mazda glc custom'
 'buick electra 225 custom' 'buick century luxus (sw)' 'buick century'
 'buick skyhawk' 'buick opel isuzu del

#### Extracting the car company names

In [135]:
# Since therer are many values of the car we will just extract the carname only
def get_brand_name(carname):
    carname = carname.split(' ')[0]
    return carname

In [140]:
get_brand_name("maruti fox")

'maruti'

In [141]:
df['CarName'] = df['CarName'].apply(get_brand_name)

In [145]:
df['CarName'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [169]:
for col in df.columns:
    print("The unique values are: "+col)
    print(df[col].unique())
    print("========\n")

The unique values are: CarName
[ 1  2  3  5  6  7  8  9 10 11  4 12 13  0 14 15 16 18 17 19 20 21 22 23
 24 25 27 26]

The unique values are: fueltype
[1 0]

The unique values are: doornumber
[1 0]

The unique values are: drivewheel
[2 1 0]

The unique values are: enginetype
[0 5 3 2 6 4 1]

The unique values are: cylindernumber
[2 3 1 4 5 6 0]

The unique values are: enginesize
[130 152 136 131 108 164 209  61  90  98 122 156  92  79 110 111 119 258
 326  91  70  80 140 134 183 234 308 304  97 103 120 181 151 194 203 132
 121 146 171 161 109 141 173 145]

The unique values are: horsepower
[111 154 110 140 160 101 121 182  48  70  68 102  88 145  58  76  60  86
 100  78  90 176 262 135  84  64 120  72 123 155 184 175 116  69  55  97
 152 200  95 142 143 207 288  73  82  94  62  56 112  92 161 156  52  85
 114 162 134 106]

The unique values are: citympg
[21 19 17 16 23 20 15 47 38 37 31 24 49 30 27 25 13 26 36 22 14 45 28 18
 32 35 34 29 33]

The unique values are: highwaympg
[27 26 25

In [149]:
df['CarName'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

### Since the some of the datasets are in categorical values we have to encode them into numerical values

In [150]:
le = LabelEncoder()

In [155]:
df['CarName'] = le.fit_transform(df['CarName'])

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11,  4, 12, 13,  0, 14, 15, 16,
       18, 17, 19, 20, 21, 22, 23, 24, 25, 27, 26])

In [167]:
df['cylindernumber'] = le.fit_transform(df['cylindernumber'])

### Checking if all the columns values have the numerical values or not

In [172]:
df.head()

CarName  fueltype  doornumber  drivewheel  enginetype  cylindernumber  \
0        1         1           1           2           0               2   
1        1         1           1           2           0               2   
2        1         1           1           2           5               3   
5        2         1           1           1           3               1   
7        2         1           0           1           3               1   

   enginesize  horsepower  citympg  highwaympg    price  
0         130         111       21          27  13495.0  
1         130         111       21          27  16500.0  
2         152         154       19          26  16500.0  
5         136         110       19          25  15250.0  
7         136         110       19          25  18920.0

In [179]:
X = df.drop(columns=['price'])
y = df[['price']]

# In the value of y i have used 2 big brackets inorder to create a 2d array

In [181]:
# from sklearn.model_creation import train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [190]:
from sklearn.linear_model import LinearRegression

In [193]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [195]:
lr.coef_

array([[ -111.31718646, -2668.01609027,  -961.29964982,  2054.0673478 ,
          360.7679451 ,  -829.1725733 ,    78.1086494 ,    63.54661124,
         -272.35343787,   121.47985435]])

In [197]:
lr.intercept_

array([2129.30952165])

In [198]:
y_pred = lr.predict(X_test)

In [202]:
y_pred 

array([[ 6432.63241215],
       [-1144.99355237],
       [ 7174.04962386],
       [ 7097.67058151],
       [ 8191.92684736],
       [ 4451.48967232],
       [29922.83053184],
       [10399.69734366],
       [ 7918.08484161],
       [29639.10651792],
       [24239.34383253],
       [ 5668.0250446 ],
       [15466.291902  ],
       [10730.77280277],
       [18590.36376282],
       [16198.44512239],
       [10426.86729286],
       [ 6917.40326881],
       [11692.07245259],
       [30884.13018166],
       [26274.18760717],
       [ 5773.67821669],
       [ 7747.19113445],
       [ 7393.93206198],
       [25200.64348235],
       [11276.51497294],
       [12835.82094147],
       [25200.64348235],
       [33894.09440981],
       [10177.7080439 ],
       [19049.93522185],
       [ 5564.66153693],
       [11837.07777053],
       [ 6211.3395947 ],
       [15466.291902  ],
       [14240.72147716],
       [ 7760.44970371],
       [ 8388.42735354],
       [15466.291902  ],
       [ 9775.21150358],


In [204]:
y_test = y_test.values

In [206]:
from sklearn.metrics import mean_squared_error,r2_score

In [207]:
mse = mean_squared_error(y_pred,y_test)
mse

14064453.108871818

In [219]:
r2_score = r2_score(y_pred,y_test)

TypeError: 'numpy.float64' object is not callable

In [220]:
r2_score

0.797900351076918

In [ ]:
sns.regplot(x=y_pred,y=y_test)