## 1. Array Creation

In [25]:
import numpy as np 

# a. Create a 1-dimensional array of integers from 1 to 10
one_dim_array = np.array(range(1,11))
print(one_dim_array)

# b. Create a 2-dimensional array of random float values of shape(3,4)
two_dim_rand_array = np.random.rand(3,4)*10
print(two_dim_rand_array)

# c. Create a three dimensional array of zeros with shape (2,3,4)
three_dim_array = np.zeros((2,3,4))
print(three_dim_array)

[ 1  2  3  4  5  6  7  8  9 10]
[[3.59344178 2.22071049 0.23075171 6.76189433]
 [8.58557425 3.806624   7.15214521 9.88511831]
 [3.41046559 0.94621516 8.74967614 6.70326203]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## 2. Array Operation

In [41]:
# a. Given two 1-dimensional arrays, perform element wise addition, substraction, multiplication and division
first_array = np.array([1,2,3])
second_array = np.array([4,5,6])

add = first_array + second_array
print(f"The sum of the two arrays: {first_array} + {second_array} = {add}")

sub = first_array - second_array
print(f"The subtraction of the two arrays: {first_array} - {second_array} = {sub}")

mul = first_array * second_array
print(f"The multiplication of the two arrays: {first_array} * {second_array} = {mul}")

div = first_array / second_array
print(f"The division of the two arrays: {first_array} / {second_array} = {div}")


# b. Calculate the mean, median, and sd of a given 1-dimensional array
new_array = np.array([1,2,3])
mean_value = np.mean(new_array)
print(f"The mean value of {new_array} is: {mean_value}")

median_value = np.median(new_array)
print(f"The median value of {new_array} is: {median_value}")

std_value = np.std(new_array)
print(f"The standard deviation of {new_array} is: {std_value}")

# c. Reshape a 1-dimensional array into a 2-dimensional array of shape(3,4)
one_dim_arr = np.array(range(1,13))
new_arr = one_dim_arr.reshape(3,4)
print(new_arr)

The sum of the two arrays: [1 2 3] + [4 5 6] = [5 7 9]
The subtraction of the two arrays: [1 2 3] - [4 5 6] = [-3 -3 -3]
The multiplication of the two arrays: [1 2 3] * [4 5 6] = [ 4 10 18]
The division of the two arrays: [1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]
The mean value of [1 2 3] is: 2.0
The median value of [1 2 3] is: 2.0
The standard deviation of [1 2 3] is: 0.816496580927726
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 3. Array Indexing and Slicing

In [49]:
# a. Extract the first row and last column of 2-dimensional array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


# b. Reverse the order of elements in 1-dimensional array
arr_a = np.array(range(1,10))
print("\nB ko answer:\n")
print(f"Before reversing elements are: {arr_a}")

print(f"After reversing the order elements are: {np.flip(arr_a)}")

# c. Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).
print("\nC ko answer:\n")



[[1 2 3]
 [4 5 6]]

B ko answer:

Before reversing elements are: [1 2 3 4 5 6 7 8 9]
After reversing the order elements are: [9 8 7 6 5 4 3 2 1]


## 4. Array Broadcasting

In [58]:
# a. Add a scalar value to each element of a 2-dimensional array.
scalar_value = np.array([[1,2,3],[4,5,6]])
print(scalar_value)

print("\nB ko answer: ")
one_dim_arr = np.array([1,2,3])
two_dim_arr = np.array([[1,2,3],[3,4,6]])
mul_arr = one_dim_arr * two_dim_arr
print(mul_arr)


[[1 2 3]
 [4 5 6]]

B ko answer: 
[[ 1  4  9]
 [ 3  8 18]]


# Question to ask sir.
3. a, c
4. meaning of scalar value
5. why the answer is different in question no b ?, what is the inverse and determinant of a square matrix?
6. 

## 5. Linear Algebra

In [76]:
# a. Calculate the dot product of two 1-dimensional array
one_arr = np.array(range(1,3))
two_arr = np.array(range(4,6))
print(f"The dot product: {np.dot(one_arr,two_arr)}")

# b. Compute the matrix multiplication of two 2-dimensional array
print("\nB ko answer")
first_two_arr = np.array([[1,2],[3,4]])
sec_two_arr = np.array([[5,6],[7,8]])
mul_val = first_two_arr * sec_two_arr
print(mul_val)

print(f"Multiplication is: {np.matmul(first_two_arr,sec_two_arr)}")

# c. Find the inverse and determinant of a square matrix
print("\nC ko answer")
sq_mat = np.array([[1,2],[2,3]])
print(f"The inverse is: {np.linalg.inv(sq_mat)}")

print(f"The determinant is: {np.linalg.det(sq_mat)}")

The dot product: 14

B ko answer
[[ 5 12]
 [21 32]]
Multiplication is: [[19 22]
 [43 50]]

C ko answer
The inverse is: [[-3.  2.]
 [ 2. -1.]]
The determinant is: -1.0
